//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiQR
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class INFORMATIONS
    {
        [Key]
        public int id { get; set; }
        public Nullable<int> id_qr { get; set; }
        public string informations1 { get; set; }
    
        public virtual QR_CODE QR_CODE { get; set; }
    }
}
