//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiQR
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class QR_CODE
    {
        public QR_CODE()
        {
            this.INFORMATIONS = new HashSet<INFORMATIONS>();
        }

        [Key]
        public int id { get; set; }
        public string qr_local { get; set; }
        public string qr_name { get; set; }
    
        public virtual ICollection<INFORMATIONS> INFORMATIONS { get; set; }
    }
}
